### ISSUE TITLE
create simple onboarding tracking dashboard

### ISSUE THREAD

**Issue by lowell80** [quolab/splunk-add-on#4]
Simple dashboard should show high-level errors, ingestion event counts per input

- [ ] slack screenshot to team

**Comment by abraidotti** [comment]
index=_internal sourcetype=quolab:modinput:timeline

default to last 24 hours

- list of what inputs are active
- list how many events have been processed (use range from start to end of day) - maybe timechart that
- list of errors
- add timechart

save at app level as demo dashboard
